### ISSUE TITLE
[FEAT] 멋사 7차 과제🦁

### ISSUE THREAD

**Issue by tigowler** [Likelion-at-SMWU-10th/ChoEunBi#14]
## 📌  Feature Issue

- 6차 과제 '나만의 다이어리'에 모델 추가하기
- '나만의 다이어리'에 회원가입 기능 추가하기

## 📝  To-do

- [ ] html에서 모델 데이터 보여주기
- [ ] Path Converter 이용하기
- [ ] 회원 가입 기능 추가하기
