### ISSUE TITLE
[FEAT] 멋사 3차 과제🦁

### ISSUE THREAD

**Issue by tigowler** [Likelion-at-SMWU-10th/ChoEunBi#8]
## 📌  Feature Issue

Python 관련 코드라이언 강의 듣고 따라 실습하기

## 📝  To-do

- [ ] '일단 만드는 PYTHON' 완강하기
- [ ] '[심화] 같이 푸는 PYTHON' 완강하기
- [ ] 강의 내 코드 실행 결과 직접 확인하기
